import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import {
  motion,
  AnimatePresence,
  useMotionValue,
  useSpring,
  useTransform,
  useMotionTemplate,
  useMotionValueEvent,
  animate,
  type MotionValue,
} from 'framer-motion';
import { Play, Maximize2, X } from 'lucide-react';
import type { StudioVideo } from '@/data/studioWork';

const SQRT3 = Math.sqrt(3);
const clamp = (v: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, v));

// Spiral out from the center across a pointy-top hex grid (Apple-Watch cluster).
// Returns axial coords in spiral order so item 0 sits dead-center.
function hexSpiral(count: number) {
  const cells: Array<{ q: number; r: number; ring: number }> = [{ q: 0, r: 0, ring: 0 }];
  const dirs = [
    [1, 0],
    [1, -1],
    [0, -1],
    [-1, 0],
    [-1, 1],
    [0, 1],
  ];
  let radius = 1;
  while (cells.length < count) {
    let q = -radius;
    let r = radius; // start corner = dir[4] * radius
    for (let side = 0; side < 6; side++) {
      for (let step = 0; step < radius; step++) {
        if (cells.length < count) cells.push({ q, r, ring: radius });
        q += dirs[side][0];
        r += dirs[side][1];
      }
    }
    radius++;
  }
  return cells;
}

type TileProps = {
  x: MotionValue<number>;
  y: MotionValue<number>;
  px: number;
  py: number;
  R: number;
  d: number;
  ring: number;
  video: StudioVideo;
  focused: boolean;
  dim: boolean;
  onClick: () => void;
};

// A single circular tile. Scale, opacity and blur all track its distance from
// the viewport center as the cluster moves — fisheye magnification + depth of
// field. The entrance pop lives on an inner layer so it never fights the
// distance-driven transforms.
const Tile = ({ x, y, px, py, R, d, ring, video, focused, dim, onClick }: TileProps) => {
  const dist = (xv: number, yv: number) => Math.hypot(px + xv, py + yv);

  const scale = useTransform([x, y], ([xv, yv]: number[]) => {
    const t = Math.min(dist(xv, yv) / R, 1);
    return 1.32 - 0.9 * t * t; // ~1.32 center → ~0.42 edge
  });
  const opacity = useTransform([x, y], ([xv, yv]: number[]) => {
    const t = Math.min(dist(xv, yv) / R, 1);
    return (1 - 0.6 * t) * (dim ? 0.4 : 1); // filtered-out tiles fade, keep color
  });
  const blurPx = useTransform([x, y], ([xv, yv]: number[]) => {
    const t = Math.min(dist(xv, yv) / R, 1);
    return (t * t * 4.5).toFixed(2); // sharp center, soft edges
  });
  const zIndex = useTransform(scale, (s) => Math.round(s * 100));
  const filter = useMotionTemplate`blur(${blurPx}px)`;

  return (
    <motion.button
      type="button"
      onClick={onClick}
      aria-label={`${video.title} — ${video.tag}`}
      style={{
        x: px,
        y: py,
        width: d,
        height: d,
        marginLeft: -d / 2,
        marginTop: -d / 2,
        scale,
        opacity,
        zIndex,
      }}
      className="absolute left-0 top-0 rounded-full outline-none"
    >
      <motion.span
        initial={{ scale: 0, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{
          delay: Math.min(ring, 6) * 0.07,
          type: 'spring',
          stiffness: 220,
          damping: 18,
        }}
        className="block h-full w-full"
      >
        <motion.span
          style={{ filter }}
          className={`group relative flex h-full w-full items-center justify-center overflow-hidden rounded-full border bg-black transition-[box-shadow,border-color] duration-300 ${
            focused
              ? 'border-primary shadow-[0_0_0_3px_hsl(var(--primary)/0.45),0_22px_60px_-18px_hsl(var(--primary)/0.7)]'
              : 'border-white/12 shadow-[0_14px_44px_-16px_rgba(0,0,0,0.75)]'
          }`}
        >
          {focused ? (
            <video
              className="h-full w-full object-cover"
              src={video.src}
              poster={video.poster}
              autoPlay
              muted
              loop
              playsInline
              preload="auto"
            />
          ) : (
            <img
              src={video.poster}
              alt={`${video.title} — ${video.tag}, AI-generated by Oltaflock Studio`}
              loading="lazy"
              className="h-full w-full object-cover"
              draggable={false}
            />
          )}

          {/* Glassy inner edge */}
          <span className="pointer-events-none absolute inset-0 rounded-full shadow-[inset_0_0_26px_rgba(0,0,0,0.5)]" />

          {/* Fullscreen affordance on the centered tile */}
          {focused && (
            <span className="pointer-events-none absolute inset-0 flex items-center justify-center opacity-0 transition-opacity duration-200 group-hover:opacity-100">
              <span className="flex h-11 w-11 items-center justify-center rounded-full border border-white/40 bg-black/45 backdrop-blur-sm">
                <Maximize2 className="text-white" size={16} />
              </span>
            </span>
          )}
        </motion.span>
      </motion.span>
    </motion.button>
  );
};

type Props = {
  videos: StudioVideo[];
  activeTag: string;
};

// Draggable, fisheye honeycomb of the studio reel. Drag / wheel / arrow-keys to
// roam; the centered clip enlarges, sharpens and plays. Release and the nearest
// tile snaps magnetically to center. Tap the centered tile to open it
// fullscreen with sound.
const HexGallery = ({ videos, activeTag }: Props) => {
  const wrapRef = useRef<HTMLDivElement>(null);
  const [dims, setDims] = useState({ w: 0, h: 0 });
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const [focused, setFocused] = useState(0);
  const [lightbox, setLightbox] = useState<StudioVideo | null>(null);
  const draggingRef = useRef(false);
  const wheelTimer = useRef<number>();

  // Pointer parallax — the whole plane leans toward the cursor in 3D.
  const tiltX = useSpring(useMotionValue(0), { stiffness: 120, damping: 18 });
  const tiltY = useSpring(useMotionValue(0), { stiffness: 120, damping: 18 });

  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const ro = new ResizeObserver(([entry]) => {
      const { width, height } = entry.contentRect;
      setDims({ w: width, h: height });
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const spacing = Math.max(58, Math.min(dims.w, dims.h) * 0.15);
  const tileD = spacing * 1.5;
  const R = Math.min(dims.w, dims.h) * 0.6 || 1;

  const cells = useMemo(() => hexSpiral(videos.length), [videos.length]);
  const positions = useMemo(
    () =>
      cells.map((c) => ({
        px: spacing * SQRT3 * (c.q + c.r / 2),
        py: spacing * 1.5 * c.r,
        ring: c.ring,
      })),
    [cells, spacing]
  );
  const posRef = useRef(positions);
  posRef.current = positions;

  const bounds = useMemo(() => {
    const exX = positions.reduce((m, p) => Math.max(m, Math.abs(p.px)), 0) + tileD;
    const exY = positions.reduce((m, p) => Math.max(m, Math.abs(p.py)), 0) + tileD;
    return { x: exX, y: exY };
  }, [positions, tileD]);

  const nearest = () => {
    const xv = x.get();
    const yv = y.get();
    let best = 0;
    let bd = Infinity;
    const p = posRef.current;
    for (let i = 0; i < p.length; i++) {
      const d = Math.hypot(p[i].px + xv, p[i].py + yv);
      if (d < bd) {
        bd = d;
        best = i;
      }
    }
    return best;
  };

  useMotionValueEvent(x, 'change', () => setFocused(nearest()));
  useMotionValueEvent(y, 'change', () => setFocused(nearest()));

  const glideTo = (i: number) => {
    const p = posRef.current[i];
    const opts = { type: 'spring' as const, stiffness: 260, damping: 32 };
    animate(x, -p.px, opts);
    animate(y, -p.py, opts);
  };

  const onTileClick = (i: number, v: StudioVideo) => {
    if (draggingRef.current) return;
    if (i === focused) setLightbox(v);
    else glideTo(i);
  };

  // Trackpad / wheel pan with an idle snap.
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const onWheel = (e: WheelEvent) => {
      e.preventDefault();
      x.set(clamp(x.get() - e.deltaX, -bounds.x, bounds.x));
      y.set(clamp(y.get() - e.deltaY, -bounds.y, bounds.y));
      window.clearTimeout(wheelTimer.current);
      wheelTimer.current = window.setTimeout(() => glideTo(nearest()), 130);
    };
    el.addEventListener('wheel', onWheel, { passive: false });
    return () => el.removeEventListener('wheel', onWheel);
  }, [bounds.x, bounds.y]);

  // Pointer parallax tilt.
  useEffect(() => {
    const el = wrapRef.current;
    if (!el) return;
    const onMove = (e: PointerEvent) => {
      const r = el.getBoundingClientRect();
      const nx = (e.clientX - r.left) / r.width - 0.5;
      const ny = (e.clientY - r.top) / r.height - 0.5;
      tiltY.set(nx * 12);
      tiltX.set(-ny * 12);
    };
    const reset = () => {
      tiltX.set(0);
      tiltY.set(0);
    };
    el.addEventListener('pointermove', onMove);
    el.addEventListener('pointerleave', reset);
    return () => {
      el.removeEventListener('pointermove', onMove);
      el.removeEventListener('pointerleave', reset);
    };
  }, [tiltX, tiltY]);

  // Keyboard: arrows hop to the neighbor in that direction, Enter plays center.
  const onKeyDown = (e: React.KeyboardEvent) => {
    const dirs: Record<string, [number, number]> = {
      ArrowRight: [1, 0],
      ArrowLeft: [-1, 0],
      ArrowDown: [0, 1],
      ArrowUp: [0, -1],
    };
    if (e.key === 'Enter') {
      e.preventDefault();
      setLightbox(videos[focused]);
      return;
    }
    const dir = dirs[e.key];
    if (!dir) return;
    e.preventDefault();
    const cur = posRef.current[focused];
    let best = -1;
    let bestScore = -Infinity;
    posRef.current.forEach((p, i) => {
      if (i === focused) return;
      const dx = p.px - cur.px;
      const dy = p.py - cur.py;
      const len = Math.hypot(dx, dy) || 1;
      const dot = (dx / len) * dir[0] + (dy / len) * dir[1];
      if (dot < 0.5) return; // roughly in the pressed direction
      const score = dot - len / R; // prefer aligned + close
      if (score > bestScore) {
        bestScore = score;
        best = i;
      }
    });
    if (best >= 0) glideTo(best);
  };

  // Lock scroll + Escape-to-close while fullscreen.
  useEffect(() => {
    if (!lightbox) return;
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setLightbox(null);
    document.addEventListener('keydown', onKey);
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
    };
  }, [lightbox]);

  return (
    <div
      ref={wrapRef}
      tabIndex={0}
      onKeyDown={onKeyDown}
      role="application"
      aria-label="Studio reel — drag or use arrow keys to browse clips"
      className="relative h-[70vh] min-h-[480px] w-full select-none overflow-hidden rounded-3xl border border-border bg-[radial-gradient(circle_at_center,hsl(var(--card))_0%,hsl(var(--background))_88%)] outline-none [perspective:1400px] focus-visible:ring-2 focus-visible:ring-primary/50"
    >
      {/* Vignette fading the cluster into the panel edges */}
      <div className="pointer-events-none absolute inset-0 z-30 bg-[radial-gradient(circle_at_center,transparent_40%,hsl(var(--background))_118%)]" />

      <motion.div
        style={{ rotateX: tiltX, rotateY: tiltY, transformStyle: 'preserve-3d' }}
        className="absolute inset-0"
      >
        <motion.div
          drag
          dragConstraints={{ left: -bounds.x, right: bounds.x, top: -bounds.y, bottom: bounds.y }}
          dragElastic={0.1}
          dragMomentum={false}
          onDragStart={() => {
            draggingRef.current = true;
          }}
          onDragEnd={() => {
            glideTo(nearest());
            window.setTimeout(() => {
              draggingRef.current = false;
            }, 60);
          }}
          style={{ x, y }}
          className="absolute left-1/2 top-1/2 h-0 w-0 cursor-grab touch-none active:cursor-grabbing"
        >
          {dims.w > 0 &&
            positions.map((p, i) => (
              <Tile
                key={videos[i].id}
                x={x}
                y={y}
                px={p.px}
                py={p.py}
                R={R}
                d={tileD}
                ring={p.ring}
                video={videos[i]}
                focused={i === focused}
                dim={activeTag !== 'All' && videos[i].tag !== activeTag}
                onClick={() => onTileClick(i, videos[i])}
              />
            ))}
        </motion.div>
      </motion.div>

      {/* Centered tile caption */}
      {videos[focused] && (
        <AnimatePresence mode="wait">
          <motion.div
            key={videos[focused].id}
            initial={{ opacity: 0, y: -6 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 6 }}
            transition={{ duration: 0.22 }}
            className="pointer-events-none absolute inset-x-0 top-5 z-30 flex flex-col items-center text-center"
          >
            <p className="text-sm font-semibold text-foreground">{videos[focused].title}</p>
            <p className="font-mono text-[11px] text-muted-foreground">{videos[focused].tag}</p>
          </motion.div>
        </AnimatePresence>
      )}

      {/* Interaction hint */}
      <div className="pointer-events-none absolute bottom-4 left-1/2 z-30 flex -translate-x-1/2 items-center gap-2 rounded-full border border-border-strong bg-card/80 px-3.5 py-1.5 text-[11px] text-muted-foreground backdrop-blur-sm">
        <Play size={11} className="text-primary" fill="currentColor" />
        Drag · scroll · arrow keys — tap center to play
      </div>

      {/* Crawler-readable list (the cluster itself is canvas-like) */}
      <ul className="sr-only">
        {videos.map((v) => (
          <li key={v.id}>
            {v.title} — {v.tag}
          </li>
        ))}
      </ul>

      {/* Fullscreen lightbox with sound */}
      {typeof document !== 'undefined' &&
        createPortal(
          <AnimatePresence>
            {lightbox && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4 backdrop-blur-sm sm:p-8"
                onClick={() => setLightbox(null)}
              >
                <button
                  type="button"
                  onClick={() => setLightbox(null)}
                  aria-label="Close fullscreen"
                  className="absolute right-4 top-4 z-10 flex h-10 w-10 items-center justify-center rounded-full border border-white/25 bg-white/10 text-white transition-colors hover:bg-white/20"
                >
                  <X size={20} />
                </button>
                <motion.div
                  initial={{ scale: 0.95, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0.97, opacity: 0 }}
                  transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
                  className="w-full max-w-5xl"
                  onClick={(e) => e.stopPropagation()}
                >
                  <video
                    className="h-auto max-h-[85vh] w-full rounded-xl bg-black"
                    src={lightbox.src}
                    poster={lightbox.poster}
                    controls
                    autoPlay
                    loop
                    playsInline
                    aria-label={`${lightbox.title} — ${lightbox.tag}, AI-generated by Oltaflock Studio`}
                  />
                  <div className="mt-3 flex items-baseline gap-3">
                    <p className="text-sm font-medium text-white">{lightbox.title}</p>
                    <p className="font-mono text-[11px] text-white/60">{lightbox.tag}</p>
                  </div>
                </motion.div>
              </motion.div>
            )}
          </AnimatePresence>,
          document.body
        )}
    </div>
  );
};

export default HexGallery;
