import { useEffect, useRef, useState, type MouseEvent } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Play, Pause, Maximize2, X } from 'lucide-react';

type Props = {
  src: string;
  poster: string;
  title: string;
  tag: string;
  /** Autoplay (muted loop) whenever the tile is in view, instead of only on hover. */
  featured?: boolean;
  className?: string;
};

// Poster-first video tile. The <video> keeps its src so play() never races an
// unset source, but preload="none" means nothing downloads until the visitor
// actually plays it (hover, click, or tap). Clicking the expand button opens a
// full-screen lightbox with native controls and sound.
const HoverVideo = ({ src, poster, title, tag, featured = false, className = '' }: Props) => {
  const ref = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const reduced =
    typeof window !== 'undefined' &&
    window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

  const play = (withSound: boolean) => {
    const el = ref.current;
    if (!el) return;
    el.muted = !withSound;
    if (withSound) el.volume = 1;
    el.play().catch(() => {});
  };

  const pause = (reset: boolean) => {
    const el = ref.current;
    if (!el) return;
    el.muted = true;
    el.pause();
    if (reset) el.currentTime = 0;
  };

  // Featured tiles autoplay (muted) once scrolled into view; pause when out.
  useEffect(() => {
    if (!featured || reduced) return;
    const el = ref.current;
    if (!el) return;
    const io = new IntersectionObserver(
      ([entry]) => (entry.isIntersecting ? play(false) : el.pause()),
      { threshold: 0.35 }
    );
    io.observe(el);
    return () => io.disconnect();
  }, [featured, reduced]);

  // Lock body scroll + close on Escape while the lightbox is open.
  useEffect(() => {
    if (!expanded) return;
    pause(false);
    const onKey = (e: KeyboardEvent) => e.key === 'Escape' && setExpanded(false);
    document.addEventListener('keydown', onKey);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [expanded]);

  // Hover / tap is a user gesture, so unmuting is allowed by autoplay policies.
  const onEnter = () => !reduced && play(true);
  const onLeave = () => (featured ? pause(false) : pause(true));

  // Explicit click toggles play/pause with sound — covers click and touch.
  const onClick = (e: MouseEvent) => {
    e.preventDefault();
    const el = ref.current;
    if (!el) return;
    if (el.paused) play(true);
    else pause(featured ? false : true);
  };

  const openLightbox = (e: MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setExpanded(true);
  };

  return (
    <>
      <div
        className={`group relative overflow-hidden rounded-xl border border-border bg-card cursor-pointer ${className}`}
        onMouseEnter={onEnter}
        onMouseLeave={onLeave}
        onClick={onClick}
      >
        <video
          ref={ref}
          className="h-full w-full object-cover transition-transform duration-[600ms] ease-out group-hover:scale-[1.04]"
          poster={poster}
          src={src}
          loop
          muted
          playsInline
          preload="none"
          onPlaying={() => setPlaying(true)}
          onPause={() => setPlaying(false)}
          aria-label={`${title} — ${tag}, AI-generated by Oltaflock Studio`}
        />

        {/* Fullscreen affordance — top-right, appears on hover */}
        <button
          type="button"
          onClick={openLightbox}
          aria-label={`Watch ${title} fullscreen`}
          className="absolute right-3 top-3 z-10 flex h-9 w-9 items-center justify-center rounded-full border border-white/30 bg-black/40 text-white opacity-0 backdrop-blur-sm transition-all duration-200 hover:bg-black/60 focus-visible:opacity-100 group-hover:opacity-100"
        >
          <Maximize2 size={16} />
        </button>

        {/* Play / pause affordance — fades while the clip runs */}
        <div
          className={`pointer-events-none absolute inset-0 flex items-center justify-center transition-opacity duration-300 ${
            playing ? 'opacity-0 group-hover:opacity-100' : 'opacity-100'
          }`}
        >
          <span className="flex h-12 w-12 items-center justify-center rounded-full border border-white/30 bg-white/15 backdrop-blur-sm transition-colors group-hover:bg-white/25">
            {playing ? (
              <Pause className="text-white" size={18} fill="currentColor" />
            ) : (
              <Play className="ml-0.5 text-white" size={18} fill="currentColor" />
            )}
          </span>
        </div>

        <div className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4">
          <p className="text-sm font-medium text-white">{title}</p>
          <p className="font-mono text-[11px] text-white/70">{tag}</p>
        </div>
      </div>

      {/* Fullscreen lightbox */}
      {typeof document !== 'undefined' && createPortal(
        <AnimatePresence>
          {expanded && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4 sm:p-8 backdrop-blur-sm"
              onClick={() => setExpanded(false)}
            >
              <button
                type="button"
                onClick={() => setExpanded(false)}
                aria-label="Close fullscreen"
                className="absolute right-4 top-4 z-10 flex h-10 w-10 items-center justify-center rounded-full border border-white/25 bg-white/10 text-white transition-colors hover:bg-white/20"
              >
                <X size={20} />
              </button>
              <motion.div
                initial={{ scale: 0.95, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.97, opacity: 0 }}
                transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
                className="w-full max-w-5xl"
                onClick={(e) => e.stopPropagation()}
              >
                <video
                  className="h-auto max-h-[85vh] w-full rounded-xl bg-black"
                  src={src}
                  poster={poster}
                  controls
                  autoPlay
                  loop
                  playsInline
                  aria-label={`${title} — ${tag}, AI-generated by Oltaflock Studio`}
                />
                <div className="mt-3 flex items-baseline gap-3">
                  <p className="text-sm font-medium text-white">{title}</p>
                  <p className="font-mono text-[11px] text-white/60">{tag}</p>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>,
        document.body
      )}
    </>
  );
};

export default HoverVideo;
