import { useEffect, useRef, useState, type MouseEvent } from 'react';
import { Play, Pause } from 'lucide-react';

type Props = {
  src: string;
  poster: string;
  title: string;
  tag: string;
  /** Autoplay (muted loop) whenever the tile is in view, instead of only on hover. */
  featured?: boolean;
  className?: string;
};

// Poster-first video tile. The <video> keeps its src so play() never races an
// unset source, but preload="none" means nothing downloads until the visitor
// actually plays it (hover, click, or tap).
const HoverVideo = ({ src, poster, title, tag, featured = false, className = '' }: Props) => {
  const ref = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(false);

  const reduced =
    typeof window !== 'undefined' &&
    window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

  const play = (withSound: boolean) => {
    const el = ref.current;
    if (!el) return;
    el.muted = !withSound;
    if (withSound) el.volume = 1;
    el.play().catch(() => {});
  };

  const pause = (reset: boolean) => {
    const el = ref.current;
    if (!el) return;
    el.muted = true;
    el.pause();
    if (reset) el.currentTime = 0;
  };

  // Featured tiles autoplay (muted) once scrolled into view; pause when out.
  useEffect(() => {
    if (!featured || reduced) return;
    const el = ref.current;
    if (!el) return;
    const io = new IntersectionObserver(
      ([entry]) => (entry.isIntersecting ? play(false) : el.pause()),
      { threshold: 0.35 }
    );
    io.observe(el);
    return () => io.disconnect();
  }, [featured, reduced]);

  // Hover / tap is a user gesture, so unmuting is allowed by autoplay policies.
  const onEnter = () => !reduced && play(true);
  const onLeave = () => (featured ? pause(false) : pause(true));

  // Explicit click toggles play/pause with sound — covers click and touch.
  const onClick = (e: MouseEvent) => {
    e.preventDefault();
    const el = ref.current;
    if (!el) return;
    if (el.paused) play(true);
    else pause(featured ? false : true);
  };

  return (
    <div
      className={`group relative overflow-hidden rounded-xl border border-border bg-card cursor-pointer ${className}`}
      onMouseEnter={onEnter}
      onMouseLeave={onLeave}
      onClick={onClick}
    >
      <video
        ref={ref}
        className="h-full w-full object-cover transition-transform duration-[600ms] ease-out group-hover:scale-[1.04]"
        poster={poster}
        src={src}
        loop
        muted
        playsInline
        preload="none"
        onPlaying={() => setPlaying(true)}
        onPause={() => setPlaying(false)}
        aria-label={`${title} — ${tag}, AI-generated by Oltaflock Studio`}
      />

      {/* Play / pause affordance — fades while the clip runs */}
      <div
        className={`pointer-events-none absolute inset-0 flex items-center justify-center transition-opacity duration-300 ${
          playing ? 'opacity-0 group-hover:opacity-100' : 'opacity-100'
        }`}
      >
        <span className="flex h-12 w-12 items-center justify-center rounded-full border border-white/30 bg-white/15 backdrop-blur-sm transition-colors group-hover:bg-white/25">
          {playing ? (
            <Pause className="text-white" size={18} fill="currentColor" />
          ) : (
            <Play className="ml-0.5 text-white" size={18} fill="currentColor" />
          )}
        </span>
      </div>

      <div className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4">
        <p className="text-sm font-medium text-white">{title}</p>
        <p className="font-mono text-[11px] text-white/70">{tag}</p>
      </div>
    </div>
  );
};

export default HoverVideo;
