import { useEffect, useRef, useState, type TouchEvent } from 'react';
import { Play } from 'lucide-react';

type Props = {
  src: string;
  poster: string;
  title: string;
  tag: string;
  /** Autoplay (muted loop) whenever the tile is in view, instead of only on hover. */
  featured?: boolean;
  className?: string;
};

// Poster-first video tile: the <video> src is only attached when needed (hover, or in-view for
// featured), so a gallery of clips stays cheap until the visitor actually engages with one.
const HoverVideo = ({ src, poster, title, tag, featured = false, className = '' }: Props) => {
  const ref = useRef<HTMLVideoElement>(null);
  const [load, setLoad] = useState(featured);
  const [playing, setPlaying] = useState(false);

  const reduced =
    typeof window !== 'undefined' &&
    window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;

  // Featured tiles begin loading + playing once scrolled into view.
  useEffect(() => {
    if (!featured || reduced) return;
    const el = ref.current;
    if (!el) return;
    const io = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setLoad(true);
          el.play().catch(() => {});
        } else {
          el.pause();
        }
      },
      { threshold: 0.35 }
    );
    io.observe(el);
    return () => io.disconnect();
  }, [featured, reduced]);

  // Hover is a user gesture, so unmuting here is allowed by autoplay policies.
  const start = () => {
    if (reduced) return;
    setLoad(true);
    const el = ref.current;
    if (el) {
      el.muted = false;
      el.volume = 1;
      el.play().catch(() => {});
    }
  };
  const stop = () => {
    const el = ref.current;
    if (!el) return;
    // Mute on leave so the in-view featured clip keeps playing silently rather than blasting audio.
    el.muted = true;
    if (featured) return;
    el.pause();
    el.currentTime = 0;
  };

  // Touch devices have no hover, so the hover-to-play model never fires. A tap
  // toggles play/pause with sound, making the gallery usable on phones.
  const handleTouch = (e: TouchEvent) => {
    if (reduced) return;
    const el = ref.current;
    if (!el) return;
    e.preventDefault();
    setLoad(true);
    if (el.paused) {
      el.muted = false;
      el.volume = 1;
      el.play().catch(() => {});
    } else {
      el.muted = true;
      el.pause();
    }
  };

  return (
    <div
      className={`group relative overflow-hidden rounded-xl border border-border bg-card ${className}`}
      onMouseEnter={start}
      onMouseLeave={stop}
      onTouchStart={handleTouch}
    >
      <video
        ref={ref}
        className="h-full w-full object-cover transition-transform duration-[600ms] ease-out group-hover:scale-[1.04]"
        poster={poster}
        src={load ? src : undefined}
        muted
        loop
        playsInline
        preload="none"
        onPlaying={() => setPlaying(true)}
        onPause={() => setPlaying(false)}
        aria-label={`${title} — ${tag}, AI-generated by Oltaflock Studio`}
      />

      {/* Play affordance — fades out while the clip is running */}
      <div
        className={`pointer-events-none absolute inset-0 flex items-center justify-center transition-opacity duration-300 ${
          playing ? 'opacity-0' : 'opacity-100'
        }`}
      >
        <span className="flex h-12 w-12 items-center justify-center rounded-full border border-white/30 bg-white/15 backdrop-blur-sm transition-colors group-hover:bg-white/25">
          <Play className="ml-0.5 text-white" size={18} fill="currentColor" />
        </span>
      </div>

      <div className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4">
        <p className="text-sm font-medium text-white">{title}</p>
        <p className="font-mono text-[11px] text-white/70">{tag}</p>
      </div>
    </div>
  );
};

export default HoverVideo;
