import { useEffect, useMemo, useState, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ChevronLeft, ChevronRight } from 'lucide-react';
import { studioImages, imageBrands } from '@/data/studioImages';

// Masonry image portfolio with a fullscreen lightbox (keyboard + swipe-safe).
const StudioGallery = () => {
  const [brand, setBrand] = useState<(typeof imageBrands)[number]>('All');
  const [open, setOpen] = useState<number | null>(null);

  const visible = useMemo(
    () => (brand === 'All' ? studioImages : studioImages.filter((i) => i.brand === brand)),
    [brand]
  );

  const close = useCallback(() => setOpen(null), []);
  const step = useCallback(
    (dir: number) => setOpen((c) => (c === null ? c : (c + dir + visible.length) % visible.length)),
    [visible.length]
  );

  // Keyboard nav + body-scroll lock while the lightbox is open.
  useEffect(() => {
    if (open === null) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') close();
      if (e.key === 'ArrowRight') step(1);
      if (e.key === 'ArrowLeft') step(-1);
    };
    document.addEventListener('keydown', onKey);
    const prev = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = prev;
    };
  }, [open, close, step]);

  const active = open === null ? null : visible[open];

  return (
    <div>
      {/* Brand filter */}
      <div className="mb-6 flex flex-wrap gap-2">
        {imageBrands.map((b) => (
          <button
            key={b}
            type="button"
            onClick={() => setBrand(b)}
            className={`h-9 rounded-full border px-4 text-sm font-medium transition-all duration-200 ${
              brand === b
                ? 'border-foreground bg-foreground text-background'
                : 'border-border-strong text-muted-foreground hover:border-foreground hover:text-foreground'
            }`}
          >
            {b}
          </button>
        ))}
      </div>

      {/* Masonry grid */}
      <div className="columns-2 gap-4 lg:columns-3 [&>*]:mb-4">
        {visible.map((img, i) => (
          <button
            key={img.src}
            type="button"
            onClick={() => setOpen(i)}
            aria-label={`View ${img.brand} — ${img.collection} fullscreen`}
            className="group relative block w-full overflow-hidden rounded-xl border border-border bg-card"
          >
            <img
              src={img.src}
              alt={`${img.brand} ${img.collection} — AI-generated by Oltaflock Studio`}
              width={img.w}
              height={img.h}
              loading="lazy"
              className="w-full transition-transform duration-500 ease-out group-hover:scale-[1.04]"
            />
            <span className="pointer-events-none absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/70 to-transparent p-3 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
              <span className="text-xs font-medium text-white">{img.brand}</span>
              <span className="font-mono text-[10px] text-white/70">{img.collection}</span>
            </span>
          </button>
        ))}
      </div>

      {/* Lightbox */}
      {typeof document !== 'undefined' &&
        createPortal(
          <AnimatePresence>
            {active && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4 backdrop-blur-sm sm:p-8"
                onClick={close}
              >
                <button
                  type="button"
                  onClick={close}
                  aria-label="Close"
                  className="absolute right-4 top-4 z-10 flex h-10 w-10 items-center justify-center rounded-full border border-white/25 bg-white/10 text-white transition-colors hover:bg-white/20"
                >
                  <X size={20} />
                </button>
                {visible.length > 1 && (
                  <>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        step(-1);
                      }}
                      aria-label="Previous"
                      className="absolute left-3 z-10 flex h-11 w-11 items-center justify-center rounded-full border border-white/25 bg-white/10 text-white transition-colors hover:bg-white/20 sm:left-6"
                    >
                      <ChevronLeft size={22} />
                    </button>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        step(1);
                      }}
                      aria-label="Next"
                      className="absolute right-3 z-10 flex h-11 w-11 items-center justify-center rounded-full border border-white/25 bg-white/10 text-white transition-colors hover:bg-white/20 sm:right-6"
                    >
                      <ChevronRight size={22} />
                    </button>
                  </>
                )}
                <motion.figure
                  key={active.src}
                  initial={{ scale: 0.96, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  transition={{ duration: 0.22, ease: [0.22, 1, 0.36, 1] }}
                  className="flex max-h-[88vh] max-w-5xl flex-col items-center"
                  onClick={(e) => e.stopPropagation()}
                >
                  <img
                    src={active.src}
                    alt={`${active.brand} ${active.collection} — AI-generated by Oltaflock Studio`}
                    className="max-h-[82vh] w-auto rounded-xl object-contain"
                  />
                  <figcaption className="mt-3 flex items-baseline gap-3">
                    <span className="text-sm font-medium text-white">{active.brand}</span>
                    <span className="font-mono text-[11px] text-white/60">{active.collection}</span>
                  </figcaption>
                </motion.figure>
              </motion.div>
            )}
          </AnimatePresence>,
          document.body
        )}
    </div>
  );
};

export default StudioGallery;
